# Generated by Django 4.2.17 on 2025-01-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_buildpost_image_alt_buildpost_image_of_build'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildpost',
            name='excerpt',
            field=models.TextField(blank=True, max_length=180),
        ),
    ]
