# Generated by Django 4.2.17 on 2025-01-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0004_alter_buildpost_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildpost',
            name='slug',
            field=models.SlugField(default='', max_length=150),
        ),
    ]
