# Generated by Django 4.2.17 on 2025-01-07 19:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0005_buildpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildpost',
            name='image_of_build',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
