# Generated by Django 4.2.17 on 2025-01-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0006_alter_buildpost_image_of_build'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='build_id',
            new_name='build_post',
        ),
    ]
