# Generated by Django 4.2.17 on 2025-01-14 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('builds', '0008_alter_buildpost_build_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildpost',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buildpost',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='buildpost',
            name='build_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='build_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='builds.buildpost'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10)),
                ('buildpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_post', to='builds.buildpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
