# Generated by Django 4.2.17 on 2025-01-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0009_buildpost_liked_buildpost_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_title',
        ),
    ]
