# Generated by Django 4.2.17 on 2025-01-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0010_remove_comment_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
