# Generated by Django 4.2.17 on 2025-01-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0011_comment_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_status',
        ),
    ]
