# Generated by Django 4.2.17 on 2025-01-25 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0012_remove_comment_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildpost',
            name='money_spent',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MaxValueValidator(999999, 99), django.core.validators.MinValueValidator(0, 0)]),
        ),
    ]
