# Generated by Django 4.2.17 on 2025-01-05 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureContentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('future_content_title', models.CharField(max_length=150, unique=True)),
                ('email_for_contact', models.EmailField(max_length=300)),
                ('future_content_description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status_of_request', models.IntegerField(choices=[(0, 'Request Sent'), (1, 'Request being looked at'), (2, 'Will be implemented'), (3, 'Denied')], default=0)),
                ('future_content_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_content_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
