# Generated by Django 4.2.17 on 2025-01-11 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('future_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurecontentrequest',
            name='future_content_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_content_request_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
